# Generated by Django 5.2 on 2025-08-09 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=6)),
                ('region_code', models.CharField(blank=True, max_length=20, null=True)),
                ('T0', models.DecimalField(decimal_places=2, max_digits=5)),
                ('T1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('T2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('T3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('month', 'region_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('recommended_bucket', models.CharField(choices=[('T0', 'T0 (06:00-08:00)'), ('T1', 'T1 (08:00-10:00)'), ('T2', 'T2 (17:00-19:00)'), ('T3', 'T3 (19:00-21:00)')], max_length=2)),
                ('window_start', models.TimeField()),
                ('window_end', models.TimeField()),
                ('expected_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_congestion_level', models.SmallIntegerField(blank=True, null=True)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', '계획됨'), ('ongoing', '진행중'), ('arrived', '도착'), ('cancelled', '취소됨')], default='planned', max_length=20)),
                ('planned_departure', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
